CREATE TABLE xuedu.question (
	ID INT NOT NULL AUTO_INCREMENT,
	INSERT_DATETIME DATETIME,
	UPDATE_DATETIME DATETIME,
	QUESTION VARCHAR(100),
	IS_ACTIVE INT DEFAULT 1,
	IS_ANSWERED INT DEFAULT 0,
	FROM_WHO VARCHAR(100),
	CONSTRAINT question_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB;

CREATE TABLE xuedu.users (
	ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(100),
	PASSWORD VARCHAR(100),
	IS_ACTIVE INT DEFAULT 1,
	CONSTRAINT users_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB;

CREATE TABLE xuedu.answer (
	ID INT NOT NULL AUTO_INCREMENT,
	INSERT_DATETIME DATETIME,
	UPDATE_DATETIME DATETIME,
	TITLE VARCHAR(100),
	ANSWER VARCHAR(100),
	IS_ACTIVE INT DEFAULT 1,
	CONSTRAINT answer_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB;
